#!/usr/bin/env bash
# =============================================================================
# optimize-media.sh — turns the originals in images/ into web-ready assets.
#
#   ./tools/optimize-media.sh
#
# Originals are never modified. Everything is written to:
#   assets/img/    responsive AVIF + WebP + JPEG ladders
#   assets/video/  H.264 MP4 (+ VP9 WebM)
#   assets/posters/  poster frames as JPEG + AVIF + WebP
#   assets/js/media.js   a manifest the site reads automatically
#
# Re-running only rebuilds what changed, so it is safe to run repeatedly.
# Every output is written to a .part file and moved into place when complete,
# so stopping the script half-way never leaves a truncated file behind.
# Requires: ImageMagick (magick), cwebp, avifenc, ffmpeg, sips (built into macOS)
#           brew install imagemagick webp libavif ffmpeg
# =============================================================================
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$PWD"
SRC="$ROOT/images"
IMGOUT="$ROOT/assets/img"
VIDOUT="$ROOT/assets/video"
POSTER="$ROOT/assets/posters"
MANIFEST="$ROOT/assets/js/media.js"

WIDTHS=(400 900 1600 2400)
VIDEO_EDGE=1280     # long edge of web video, px
JPEG_Q=82
WEBP_Q=78
AVIF_Q=52           # chosen by measurement: ~36% smaller than WebP 78 at the same SSIM,
                    # and visibly cleaner in dark stage shadows

for bin in magick cwebp avifenc ffmpeg sips; do
  command -v "$bin" >/dev/null || { echo "✗ missing '$bin' — brew install imagemagick webp libavif ffmpeg"; exit 1; }
done

mkdir -p "$IMGOUT" "$VIDOUT" "$POSTER"

# "7 (32).jpg" -> "7-32"
# BSD sed (macOS) has no \+ in basic regex, so -E is required here.
slugify() {
  printf '%s' "$1" \
    | sed 's/\.[^.]*$//' \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//'
}

# Two sources can slugify to the same name ("little_girl.mp4" and
# "little_girl_.m4v" are both "little-girl"). They must not share output files,
# or one silently overwrites — or masks — the other. The first keeps the plain
# name; later ones get their extension appended ("little-girl-m4v").
#
# Sets $SLUG rather than printing it: $(…) would run in a subshell and forget
# which names were already taken. Photos and videos write to different folders,
# so each list starts afresh.
USED_SLUGS=" "
unique_slug() {
  local name="$1" ext
  SLUG="$(slugify "$name")"
  if [[ "$USED_SLUGS" == *" $SLUG "* ]]; then
    ext="$(printf '%s' "${name##*.}" | tr '[:upper:]' '[:lower:]')"
    SLUG="$SLUG-$ext"
    echo "   ! $name has the same web name as another file — writing it as $SLUG"
  fi
  USED_SLUGS="$USED_SLUGS$SLUG "
}

echo "→ images"
tmp_manifest="$(mktemp)"
printf '/* Generated by tools/optimize-media.sh — do not edit by hand. */\nwindow.MEDIA = {\n  images: {\n' > "$tmp_manifest"

shopt -s nullglob nocaseglob
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

for f in "$SRC"/*.jpg "$SRC"/*.jpeg "$SRC"/*.png "$SRC"/*.heic "$SRC"/*.heif; do
  base_name="$(basename "$f")"
  unique_slug "$base_name"; slug="$SLUG"
  top="$IMGOUT/$slug-400.avif"

  # One lossless, upright, sRGB master per photo; every format is encoded from
  # it, so nothing is compressed twice. HEIC goes through macOS sips, because
  # ImageMagick on this machine has no HEIC decoder (and browsers other than
  # Safari can't show HEIC at all).
  master="$WORK/master.png"
  if [[ "$base_name" =~ \.[Hh][Ee][Ii][CcFf]$ ]]; then
    sips -s format png "$f" --out "$WORK/heic.png" >/dev/null
    magick "$WORK/heic.png" -auto-orient -colorspace sRGB -strip "png24:$master"
  else
    magick "$f[0]" -auto-orient -colorspace sRGB -strip "png24:$master"
  fi
  sw=$(magick identify -format '%w' "$master")
  sh=$(magick identify -format '%h' "$master")

  built=()
  for w in "${WIDTHS[@]}"; do
    # Never upscale. When the source falls between two sizes, its own width
    # becomes the top size — so a 2048px photo gets 400/900/1600/2048.
    tw=$(( w > sw ? sw : w ))
    if [ "${#built[@]}" -gt 0 ] && [ "$tw" -le "${built[${#built[@]}-1]}" ]; then break; fi
    jpg="$IMGOUT/$slug-$tw.jpg"; webp="$IMGOUT/$slug-$tw.webp"; avif="$IMGOUT/$slug-$tw.avif"

    if [ ! -f "$jpg" ] || [ ! -f "$webp" ] || [ ! -f "$avif" ] || [ "$f" -nt "$jpg" ]; then
      rung="$WORK/rung.png"
      magick "$master" -resize "${tw}x>" "png24:$rung"
      magick "$rung" -interlace Plane -quality "$JPEG_Q" "jpg:$jpg.part" && mv "$jpg.part" "$jpg"
      cwebp -quiet -q "$WEBP_Q" -metadata none "$rung" -o "$webp.part" && mv "$webp.part" "$webp"
      avifenc -q "$AVIF_Q" -s 6 --yuv 420 -j all "$rung" "$avif.part.avif" >/dev/null && mv "$avif.part.avif" "$avif"
    fi
    built+=("$tw")
  done

  # A 24px blurred thumbnail, inlined as a data URI so it costs no request.
  lqip=$(magick "$master" -resize 24x -blur 0x1.2 -strip -quality 40 jpg:- | base64 | tr -d '\n')

  widths_json=$(printf '%s,' "${built[@]}" | sed 's/,$//')
  printf '    "%s": { base: "assets/img/%s", widths: [%s], w: %s, h: %s, avif: true, lqip: "data:image/jpeg;base64,%s" },\n' \
    "$base_name" "$slug" "$widths_json" "$sw" "$sh" "$lqip" >> "$tmp_manifest"

  echo "   ✓ $base_name → ${#built[@]} sizes"
done

printf '  },\n  videos: {\n' >> "$tmp_manifest"

echo "→ videos"
USED_SLUGS=" "
for v in "$SRC"/*.mov "$SRC"/*.mp4 "$SRC"/*.m4v; do
  base_name="$(basename "$v")"
  unique_slug "$base_name"; slug="$SLUG"
  mp4="$VIDOUT/$slug.mp4"
  webm="$VIDOUT/$slug.webm"
  post="$POSTER/$slug.jpg"

  if [ ! -f "$mp4" ] || [ "$v" -nt "$mp4" ]; then
    echo "   · $base_name → mp4"
    # Cap the long edge (phone rotation is applied first), keep even
    # dimensions, cap the bitrate, and move the moov atom to the front so
    # playback starts before the file finishes downloading.
    ffmpeg -v error -y -i "$v" \
      -vf "scale='if(gt(iw,ih),min($VIDEO_EDGE,iw),-2)':'if(gt(iw,ih),-2,min($VIDEO_EDGE,ih))',format=yuv420p" \
      -c:v libx264 -preset slow -crf 25 -maxrate 2500k -bufsize 5000k -profile:v high -level 4.1 \
      -c:a aac -b:a 128k -movflags +faststart -f mp4 "$mp4.part"
    mv "$mp4.part" "$mp4"
  fi

  if [ ! -f "$webm" ] || [ "$v" -nt "$webm" ]; then
    echo "   · $base_name → webm"
    ffmpeg -v error -y -i "$mp4" \
      -c:v libvpx-vp9 -crf 36 -b:v 0 -row-mt 1 -c:a libopus -b:a 96k -f webm "$webm.part"
    mv "$webm.part" "$webm"
  fi

  if [ ! -f "$post" ] || [ "$v" -nt "$post" ]; then
    ffmpeg -v error -y -ss 2 -i "$mp4" -frames:v 1 -q:v 4 "$post"
  fi

  dur=$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$mp4" | cut -d. -f1)
  printf '    "%s": { mp4: "assets/video/%s.mp4", webm: "assets/video/%s.webm", poster: "assets/posters/%s.jpg", seconds: %s },\n' \
    "$base_name" "$slug" "$slug" "$slug" "${dur:-0}" >> "$tmp_manifest"
  echo "   ✓ $base_name"
done

printf '  },\n  posters: [\n' >> "$tmp_manifest"

# Poster frames, including any you swapped in by hand: AVIF + WebP copies at up
# to 1280px (the videos' own size). The JPEG stays as the fallback. Only posters
# listed here get <picture> sources, so a poster added without re-running this
# script still shows (as its JPEG) instead of pointing at a missing file.
echo "→ posters"
for pj in "$POSTER"/*.jpg; do
  pstem="${pj%.*}"
  if [ ! -f "$pstem.avif" ] || [ ! -f "$pstem.webp" ] || [ "$pj" -nt "$pstem.avif" ]; then
    magick "$pj[0]" -auto-orient -colorspace sRGB -strip -resize "1280x1280>" "png24:$WORK/poster.png"
    avifenc -q "$AVIF_Q" -s 6 --yuv 420 -j all "$WORK/poster.png" "$pstem.part.avif" >/dev/null && mv "$pstem.part.avif" "$pstem.avif"
    cwebp -quiet -q "$WEBP_Q" -metadata none "$WORK/poster.png" -o "$pstem.webp.part" && mv "$pstem.webp.part" "$pstem.webp"
    echo "   ✓ $(basename "$pj") → avif + webp"
  fi
  printf '    "assets/posters/%s",\n' "$(basename "$pj")" >> "$tmp_manifest"
done

printf '  ]\n};\n' >> "$tmp_manifest"
mv "$tmp_manifest" "$MANIFEST"

echo
echo "✓ done"
echo "  originals : $(du -sh "$SRC" | cut -f1)"
echo "  shipped   :"
du -sh "$IMGOUT" "$VIDOUT" "$POSTER" | sed 's/^/    /' 
echo
echo "  manifest  : assets/js/media.js"
echo "  The site picks this up automatically on the next reload."
